### ISSUE TITLE
Question: how to provide site-key for Terraform deploy

### ISSUE THREAD

**Issue by vitalykarasik** [Sentinel-One/helm-charts#228]
Is there an example how deploy this chart using Terraform and provide secret values using K8S secrets? Docker pull credential works, but not site key. 

I'm using the following code, but getting 
"Error: template: s1-agent/templates/common/secrets.yaml:1:7: executing "s1-agent/templates/common/secrets.yaml" at <include "site_key.secret.create" .>: error calling include: template: s1-agent/templates/_helpers.tpl:168:17: executing "site_key.secret.create" at <.Values.secrets.site_key.value>: can't evaluate field value in type interface {}"

main.tf
```
data "aws_secretsmanager_secret_version" "sentinelone_site_token" {
  secret_id = "sentinelone-site-token"
}

resource "kubernetes_secret" "sentinelone_site_token" {
  metadata {
    name = "sentinelone-site-token"
    namespace = kubernetes_namespace.sentinelone.metadata[0].name
  }

  data = {
    site-key = data.aws_secretsmanager_secret_version.sentinelone_site_token.secret_string
  }

  type = "Opaque"
}

resource "helm_release" "sentinelone" {
  name       = "s1"
  chart      = "s1-agent"
  repository = "https://sentinel-one.github.io/helm-charts/"
  version    = "24.3.3"
  namespace  = kubernetes_namespace.sentinelone.metadata[0].name

  values = [file("${path.module}/values.yaml")]

  depends_on = [
    kubernetes_secret.pull_secret,
    kubernetes_secret.sentinelone_site_token
  ]
}
```

values.yaml
```
secrets:
  site_key: "sentinelone-site-token"
  imagePullSecret: "docker-pull-secret"

configuration:
  inventory_only: false
  repositories:
    agent: containers.sentinelone.net/cws-agent/s1agent
    helper: containers.sentinelone.net/cws-agent/s1helper
  priorityClassName: "system-node-critical"
  tag:
    agent: 24.3.3-x86_64-ga
    helper: 24.3.3-x86_64-ga
```
